# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: EmptyRepo
      type: github
      endpoint: github.com_surveyjsdeveloper
      name: surveyjs/azure-pipelines-repo-dont-remove-please
  pipelines:
    - pipeline: LibraryMain
      source: Library Main
      trigger: none

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  CurrentBranch: $(Build.SourceBranchName)
  ProjectId: "d79f2855-7b94-4261-9daf-4cace0a06c03"

trigger: none

pr:
  branches:
    include:
      - master

pool:
  vmImage: "Ubuntu-22.04"

steps:
  - checkout: self
  - checkout: EmptyRepo
    persistCredentials: true
    clean: true
    fetchDepth: 1

  - download: LibraryMain
    artifact: SurveyJSLibraryBuildCore

  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/"
      Contents: "package.json"
      TargetFolder: "$(Build.SourcesDirectory)/Temp/"
      OverWrite: true
    displayName: "Copy package.json for cache key"

  - task: Cache@2
    inputs:
      key: "npm-cache-analytics | $(Build.SourcesDirectory)/Temp/package.json"
      path: $(Build.SourcesDirectory)/node_modules
      cacheHitVar: NPM_CACHE_RESTORED
    displayName: Cache NPM

  - powershell: |
      $env:GIT_REDIRECT_STDERR = '2>&1'
      git config --global user.email "surveyjs.org@gmail.com"
      git config --global user.name "surveyjsdeveloper"
    displayName: "Set up Git config"

  - task: Npm@1
    displayName: "NPM install"
    inputs:
      command: custom
      customCommand: install --legacy-peer-deps
      verbose: false
      workingDir: $(Build.SourcesDirectory)
    condition: ne(variables.NPM_CACHE_RESTORED, 'true')

  - script: |
      cd $(Build.SourcesDirectory)
      npm run lint
    displayName: "run lint command"

  - script: |
      cd $(Build.SourcesDirectory)
      npm run pwinst
    displayName: "Install chrome playwright"

  - script: |
      cd $(Build.SourcesDirectory)/node_modules
      rm -rf survey-core
    displayName: "remove survey-core symlink from node_modules"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Pipeline.Workspace)/LibraryMain/SurveyJSLibraryBuildCore/packages/survey-core"
      Contents: "**"
      TargetFolder: "$(Build.SourcesDirectory)/node_modules/survey-core"
      OverWrite: true

  # npm run release with version
  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Pipeline.Workspace)/LibraryMain/SurveyJSLibraryBuildCore/"
      Contents: "version.txt"
      TargetFolder: "$(Build.SourcesDirectory)/"
      OverWrite: true
    displayName: "Copy Build Artifact - SurveyJSVersion File"

  - script: |
      cd $(Build.SourcesDirectory)
      npm run build:all
    displayName: "NPM build"

  - script: |
      cd $(Build.SourcesDirectory)
      npm run build:types:summary:core
      npm run build:types:summary
      npm run build:types:tabulator
    displayName: "NPM build typings"

  - script: |
      cd $(Build.SourcesDirectory)
      npm test
    displayName: "Run unit tests"

  - script: |
      cd $(Build.SourcesDirectory)
      npm run e2e:ci
    displayName: "Run E2E tests"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura # or JaCoCo
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.SourcesDirectory)/test-results"
      ArtifactName: "e2e"
      publishLocation: "Container"
    condition: always()
    displayName: "Publish E2E artifacts"

  - task: PublishTestResults@2
    displayName: "Publish e2e test results"
    inputs:
      searchFolder: "$(Build.SourcesDirectory)/test-results"
      testResultsFormat: "JUnit"
      testResultsFiles: "e2e-junit-results.xml"
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: "Publish E2E test results"
    condition: succeededOrFailed()
